Fix NoMethodError for Zestimateable when valueChange doesn't have a duration attribute
Sometimes <valueChange> inside <rentzestimate> doesn't have a duration
attribute.  This caused a NoMethodError: undefined method 'value' for
nil:NilClass error.