No longer call #chomp on the end of value duration
According to the ruby documentation, #chomp removes new line characters
such as \r\n or \n from the end of a string.  I don't see any reason to
expect these to be in the duration attribute, and it causes this error
when duration is not present:

NoMethodError: undefined method `chomp' for nil:NilClass